spring:
  config:
    import: optional:file:.env[.properties]
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT_TLS}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: false
          ssl:
            enable: true
          ssl.trust: ${SMTP_HOST}
      debug: true
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.example.mail_service.dto.KafkaMessageDto  # Полный путь!
        spring.json.trusted.packages: com.example.mail_service.dto  # Только нужные пакеты
        spring.json.add.type.headers: false
topics:
  user-topic: email-message-topic

server:
#  frontend-url: http://localhost:4201
  port: 8081